# Generated by Django 5.0.7 on 2024-10-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_user_chatmessage_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
